name: Update Events JSON

on:
  schedule:
    - cron: "0 */6 * * *"   # cada 6 horas
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build events.json from ICS
        env:
          ICS_URL: ${{ secrets.ICS_URL }}
        run: |
          node scripts/build-events.js

      - name: Commit changes (if any)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/events.json
            git commit -m "chore(events): auto-update events.json from ICS"
            git push
          else
            echo "No changes."
          fi
